/** app/admin 공통 스타일 — 섹션 컴포넌트 간 공유 */
export const S: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#faf7f1",
    color: "#2c2c30",
    fontFamily: "'Apple SD Gothic Neo','Malgun Gothic',sans-serif",
    padding: "40px 20px",
  },
  sheet: { maxWidth: 820, margin: "0 auto" },
  title: { color: "#1f3b63", fontSize: "1.6rem", margin: "0 0 6px" },
  sub: { color: "#5a5f6a", fontSize: "0.9rem", margin: "0 0 20px" },
  msg: {
    background: "#eef4ff",
    border: "1px solid #c5d6f0",
    color: "#1f3b63",
    borderRadius: 8,
    padding: "10px 14px",
    marginBottom: 16,
    fontSize: "0.9rem",
  },
  empty: {
    background: "#fff",
    border: "1px solid #e3ddd1",
    borderRadius: 12,
    padding: "40px",
    textAlign: "center",
    color: "#5a5f6a",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    background: "#fff",
    borderRadius: 12,
    overflow: "hidden",
    boxShadow: "0 1px 6px rgba(31,59,99,0.06)",
  },
  th: {
    textAlign: "left",
    padding: "12px 14px",
    background: "#efe9dd",
    color: "#1f3b63",
    fontSize: "0.85rem",
  },
  td: {
    padding: "12px 14px",
    borderTop: "1px solid #e3ddd1",
    fontSize: "0.9rem",
  },
  chipB: {
    background: "#eef0f3",
    color: "#34507a",
    borderRadius: 12,
    padding: "2px 10px",
    fontSize: "0.8rem",
  },
  chipP: {
    background: "#1f3b63",
    color: "#fff",
    borderRadius: 12,
    padding: "2px 10px",
    fontSize: "0.8rem",
  },
  link: { color: "#3b6fb5", textDecoration: "none", fontWeight: 600 },
  approve: {
    background: "#1f3b63",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "7px 14px",
    marginRight: 6,
    cursor: "pointer",
    fontSize: "0.85rem",
  },
  reject: {
    background: "#fff",
    color: "#a33",
    border: "1px solid #e0b4b0",
    borderRadius: 8,
    padding: "7px 14px",
    cursor: "pointer",
    fontSize: "0.85rem",
  },
  section: {
    color: "#1f3b63",
    fontSize: "1.2rem",
    margin: "36px 0 6px",
  },
  statusRej: {
    background: "#fdf0ee",
    color: "#a33",
    borderRadius: 12,
    padding: "2px 10px",
    fontSize: "0.8rem",
  },
  statusFail: {
    background: "#fff8ec",
    color: "#9a6200",
    borderRadius: 12,
    padding: "2px 10px",
    fontSize: "0.8rem",
  },
  errText: {
    color: "#a33",
    fontSize: "0.85rem",
  },
};
